apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRoleBinding
metadata:
    name: proteus-aws-operator-proxy-rolebinding
roleRef:
    kind: ClusterRole
{{ else }}
kind: RoleBinding
metadata:
    name: proteus-aws-operator-proxy-rolebinding
roleRef:
    kind: Role
{{ end }}    
    apiGroup: rbac.authorization.k8s.io
    name: proteus-aws-operator-proxy-role
subjects:
    - kind: ServiceAccount
      name: {{ include "service-account.name" . }}
      namespace: {{ .Release.Namespace }}
