apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
    name: proteus-aws-operator-proxy-role
{{ else }}    
kind: Role
metadata:
    name: proteus-aws-operator-proxy-role
{{ end }}
rules:
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
