apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        control-plane: controller-manager
    name: proteus-aws-operator-controller-manager
    namespace: {{ .Release.Namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            control-plane: controller-manager
    template:
        metadata:
            annotations:
            {{- range $key, $value := .Values.deployment.annotations }}
              {{ $key }}: {{ $value | quote }}
            {{- end }}            
            labels:
              control-plane: controller-manager      
      {{- range $key, $value := .Values.deployment.labels }}
              {{ $key }}: {{ $value | quote }}
      {{- end }}
        spec:
            containers:
                - args:
                    - --secure-listen-address=0.0.0.0:8443
                    - --upstream=http://127.0.0.1:8080/
                    - --logtostderr=true
                    - --v=10
                  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                  name: kube-rbac-proxy
                  ports:
                    - containerPort: 8443
                      name: https
                - args:
                    - --health-probe-bind-address=:8081
                    - --metrics-bind-address=127.0.0.1:8080
                    - --leader-elect
                    - --watch-namespace
                    - "$(ACK_WATCH_NAMESPACE)"
                    - --deletion-policy
                    - "$(DELETION_POLICY)"                    
                  command:
                    - /manager
                  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8081
                    initialDelaySeconds: 15
                    periodSeconds: 20
                  name: manager
                  env:
                  - name: POD_UID
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.uid
                  - name: ACK_SYSTEM_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: ACK_WATCH_NAMESPACE
                    value: {{ include "watch-namespace" . }}
                  - name: DELETION_POLICY
                    value: {{ .Values.deletionPolicy }}                                     
                  readinessProbe:
                    httpGet:
                        path: /readyz
                        port: 8081
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  resources:
                    limits:
                        cpu: 100m
                        memory: 128Mi
                    requests:
                        cpu: 50m
                        memory: 64Mi
                  securityContext:
                    allowPrivilegeEscalation: false
            securityContext:
                runAsNonRoot: false
            serviceAccountName: {{ include "service-account.name" . }}
            {{- if .Values.image.pullSecrets }}
            imagePullSecrets:
            {{- range .Values.image.pullSecrets }}
              - name: {{ . }}
            {{- end }}
            {{- end }}            
            terminationGracePeriodSeconds: 10
