{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        controller: proteus-aws-operator
    name: proteus-aws-operator-controller-manager
    namespace: {{ .Release.Namespace }}
    annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
        {{ $key }}: {{ $value | quote }}
    {{- end }}    
{{- end }}